<script setup lang="ts">
import { computed, inject, ref, unref, watch, type Ref } from 'vue'

type AutoGenerateMode = 'create' | 'update'

const props = withDefaults(
  defineProps<{
    value?: string | null
    disabled?: boolean
    field?: string
    primaryKey?: string | number | null
    source?: string | null
    maxLength?: number | null
    autoGenerate?: AutoGenerateMode[]
    placeholder?: string | null
  }>(),
  {
    value: null,
    disabled: false,
    field: '',
    primaryKey: null,
    source: '{{title}}',
    maxLength: 280,
    autoGenerate: () => ['create', 'update'],
    placeholder: null,
  },
)

const emit = defineEmits<{
  input: [value: string | null]
}>()

const injectedValues = inject<Ref<Record<string, unknown>> | Record<string, unknown> | null>(
  'values',
  null,
)

/** Last value we wrote via auto-fill — used so we keep syncing until the user edits. */
const lastAutoValue = ref<string | null>(null)
const isDirty = ref(false)

const formValues = computed((): Record<string, unknown> => {
  if (!injectedValues) {
    return {}
  }

  const raw = unref(injectedValues)

  if (raw && typeof raw === 'object') {
    return raw as Record<string, unknown>
  }

  return {}
})

const generated = computed((): string => {
  if (!props.source) {
    return ''
  }

  const rendered = renderTemplate(props.source, formValues.value)
  const plain = htmlToPlainText(rendered)
  const limit = props.maxLength && props.maxLength > 0 ? props.maxLength : 280

  return truncatePlainText(plain, limit)
})

const isCreateMode = computed((): boolean => {
  const key = props.primaryKey
  return key === '+' || key === null || key === undefined || key === ''
})

const shouldAutoGenerate = computed((): boolean => {
  if (props.disabled) {
    return false
  }

  const mode: AutoGenerateMode = isCreateMode.value ? 'create' : 'update'
  return props.autoGenerate.includes(mode)
})

const showRegenerate = computed((): boolean => {
  return (
    isDirty.value &&
    generated.value.length > 0 &&
    (props.value || '') !== generated.value
  )
})

watch(
  [generated, shouldAutoGenerate, () => props.value],
  () => {
    syncFromSource()
  },
  { immediate: true, flush: 'post' },
)

watch(
  formValues,
  () => {
    syncFromSource()
  },
  { deep: true, flush: 'post' },
)

function syncFromSource(): void {
  if (!shouldAutoGenerate.value || isDirty.value) {
    return
  }

  const next = generated.value
  const normalized = next.length > 0 ? next : null

  if ((props.value || null) === normalized) {
    lastAutoValue.value = normalized
    return
  }

  // Keep following the source while empty or still equal to the last auto value.
  const current = props.value || null
  const stillAuto =
    current === null || current === '' || current === lastAutoValue.value

  if (!stillAuto) {
    isDirty.value = true
    return
  }

  lastAutoValue.value = normalized
  emit('input', normalized)
}

function onManualInput(next: string): void {
  if (props.disabled) {
    return
  }

  if (next.length === 0) {
    isDirty.value = false
    lastAutoValue.value = null
    emit('input', null)
    syncFromSource()
    return
  }

  // Echo from our own auto-fill — do not lock sync.
  if (next === generated.value || next === lastAutoValue.value) {
    lastAutoValue.value = next
    return
  }

  isDirty.value = true
  emit('input', next)
}

function resetToAutoGenerated(): void {
  isDirty.value = false
  lastAutoValue.value = generated.value || null
  emit('input', generated.value || null)
}

function renderTemplate(template: string, record: Record<string, unknown>): string {
  return template.replace(/\{\{\s*([^}]+)\s*\}\}/g, (_match, rawKey: string) => {
    const key = rawKey.trim()
    const value = record[key]

    if (value == null) {
      return ''
    }

    return String(value)
  })
}

function htmlToPlainText(input: string): string {
  if (!input) {
    return ''
  }

  // Plain title text — skip heavy HTML work when there are no tags.
  if (!/[<>]/.test(input)) {
    return input.replace(/\s+/g, ' ').trim()
  }

  const withBreaks = input
    .replace(/<\s*br\s*\/?\s*>/gi, '\n')
    .replace(/<\/\s*(p|div|h[1-6]|li|tr)\s*>/gi, '\n')
    .replace(/<[^>]+>/g, ' ')

  const decoder = document.createElement('textarea')
  decoder.innerHTML = withBreaks

  return decoder.value
    .replace(/\u00a0/g, ' ')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{2,}/g, '\n')
    .replace(/[ \t]{2,}/g, ' ')
    .trim()
}

function truncatePlainText(text: string, maxLength: number): string {
  if (text.length <= maxLength) {
    return text
  }

  const sliced = text.slice(0, maxLength)
  const lastSpace = sliced.lastIndexOf(' ')
  const cut = lastSpace > maxLength * 0.6 ? sliced.slice(0, lastSpace) : sliced

  return `${cut.trimEnd()}…`
}
</script>

<template>
  <div class="auto-fill-text">
    <v-textarea
      :model-value="value ?? ''"
      :disabled="disabled"
      :placeholder="placeholder || undefined"
      @update:model-value="onManualInput"
    />

    <div v-if="showRegenerate" class="auto-fill-text__actions">
      <v-button x-small secondary @click="resetToAutoGenerated">
        Regenerate from source
      </v-button>
    </div>
  </div>
</template>

<style scoped>
.auto-fill-text {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.auto-fill-text__actions {
  display: flex;
  justify-content: flex-end;
}
</style>
