#!/bin/sh
# ──────────────────────────────────────────────────────────────────────────────
# Seed dynamic public content collections in Directus.
#
# Creates/updates records idempotently for:
#   - memorial_entries
#   - gallery_categories
#   - gallery_items
#   - faculties
#   - faculty_departments
#   - vacancies
#
# Also uploads mock image files (if missing) and links them from memorial/gallery.
# ──────────────────────────────────────────────────────────────────────────────
set -eu

API="${PUBLIC_URL:-http://localhost:8055}"
EMAIL="${ADMIN_EMAIL:?ADMIN_EMAIL must be set}"
PASSWORD="${ADMIN_PASSWORD:?ADMIN_PASSWORD must be set}"

log() { printf '[seed-content] %s\n' "$*"; }

extract_first_id() {
  printf '%s' "$1" | sed -n 's/.*"id":"\([^"]*\)".*/\1/p'
}

api_json() {
  # $1 = method, $2 = path, $3 (optional) = json body
  if [ "$#" -ge 3 ]; then
    curl -sS -X "$1" "$API$2" -H "$AUTH" -H 'Content-Type: application/json' -d "$3"
  else
    curl -sS -X "$1" "$API$2" -H "$AUTH"
  fi
}

api_file_upload() {
  # $1 = file path, $2 = filename_download
  curl -sS -X POST "$API/files" \
    -H "$AUTH" \
    -F "file=@$1;filename=$2"
}

upsert_single() {
  # $1 collection, $2 query_url, $3 create_json, $4 update_json
  COLLECTION=$1
  QUERY_URL=$2
  CREATE_BODY=$3
  UPDATE_BODY=$4

  FOUND=$(api_json GET "$QUERY_URL")
  FOUND_ID=$(extract_first_id "$FOUND")

  if [ -n "$FOUND_ID" ]; then
    api_json PATCH "/items/$COLLECTION/$FOUND_ID" "$UPDATE_BODY" >/dev/null
    printf '%s' "$FOUND_ID"
    return
  fi

  CREATED=$(api_json POST "/items/$COLLECTION" "$CREATE_BODY")
  CREATED_ID=$(extract_first_id "$CREATED")
  if [ -z "$CREATED_ID" ]; then
    log "Failed to create item in $COLLECTION. Response: $CREATED"
    exit 1
  fi
  printf '%s' "$CREATED_ID"
}

ensure_file() {
  # $1 filename_download, $2 local_path
  FILE_NAME=$1
  LOCAL_PATH=$2
  FOUND=$(api_json GET "/files?filter%5Bfilename_download%5D%5B_eq%5D=$FILE_NAME&fields=id,filename_download&limit=1")
  FILE_ID=$(extract_first_id "$FOUND")
  if [ -n "$FILE_ID" ]; then
    printf '%s' "$FILE_ID"
    return
  fi

  UPLOADED=$(api_file_upload "$LOCAL_PATH" "$FILE_NAME")
  FILE_ID=$(extract_first_id "$UPLOADED")
  if [ -z "$FILE_ID" ]; then
    log "Failed to upload file $FILE_NAME. Response: $UPLOADED"
    exit 1
  fi
  printf '%s' "$FILE_ID"
}

log "Logging in as $EMAIL..."
LOGIN_RESPONSE=$(
  curl -sS -X POST "$API/auth/login" \
    -H 'Content-Type: application/json' \
    -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}"
)
TOKEN=$(printf '%s' "$LOGIN_RESPONSE" | sed -n 's/.*"access_token":"\([^"]*\)".*/\1/p')
if [ -z "$TOKEN" ]; then
  log "Login failed: $LOGIN_RESPONSE"
  exit 1
fi
AUTH="Authorization: Bearer $TOKEN"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT INT TERM

# Tiny 1x1 transparent PNG used as deterministic mock media.
MOCK_PNG_BASE64='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAoMBgX6lz2EAAAAASUVORK5CYII='

make_mock_image() {
  # $1 output path
  printf '%s' "$MOCK_PNG_BASE64" | base64 -d >"$1"
}

make_mock_document() {
  # $1 output path, $2 title
  printf '%s\n%s\n%s\n' \
    "KNPU mock document seed" \
    "$2" \
    "Generated by snapshots/seed-content.sh for deterministic uploads." >"$1"
}

GALLERY_IMAGE_1="$TMP_DIR/gallery-campus-a.png"
GALLERY_IMAGE_2="$TMP_DIR/gallery-campus-b.png"
MEMORIAL_IMAGE_1="$TMP_DIR/memorial-entry-a.png"
MEMORIAL_IMAGE_2="$TMP_DIR/memorial-entry-b.png"

make_mock_image "$GALLERY_IMAGE_1"
make_mock_image "$GALLERY_IMAGE_2"
make_mock_image "$MEMORIAL_IMAGE_1"
make_mock_image "$MEMORIAL_IMAGE_2"

STUDENT_SCHEDULE_DOC_1="$TMP_DIR/student-schedule-pp101-autumn-2025.pdf"
STUDENT_SCHEDULE_DOC_2="$TMP_DIR/student-schedule-it201-spring-2025.pdf"
STUDENT_SCHEDULE_DOC_3="$TMP_DIR/student-schedule-his301-autumn-2024.pdf"
STUDENT_SCHEDULE_DOC_4="$TMP_DIR/student-schedule-math401-spring-2024.pdf"
EXAM_PROGRAMME_DOC_1="$TMP_DIR/exam-program-ukrainian-language.pdf"
EXAM_PROGRAMME_DOC_2="$TMP_DIR/exam-program-mathematics.pdf"
EXAM_PROGRAMME_DOC_3="$TMP_DIR/exam-program-history.pdf"
EXAM_PROGRAMME_DOC_4="$TMP_DIR/exam-program-pedagogy.pdf"
EXAM_PROGRAMME_DOC_5="$TMP_DIR/exam-program-computer-science.pdf"
EXAM_PROGRAMME_DOC_6="$TMP_DIR/exam-program-psychology.pdf"
UNIVERSITY_ORDER_DOC_1="$TMP_DIR/university-order-001-2024.pdf"
UNIVERSITY_ORDER_DOC_2="$TMP_DIR/university-order-002-2024.pdf"
UNIVERSITY_ORDER_DOC_3="$TMP_DIR/university-order-003-2024.pdf"
UNIVERSITY_ORDER_DOC_4="$TMP_DIR/university-order-001-2025.pdf"
UNIVERSITY_ORDER_DOC_5="$TMP_DIR/university-order-002-2025.pdf"
UNIVERSITY_ORDER_DOC_6="$TMP_DIR/university-order-003-2025.pdf"
UNIVERSITY_ORDER_DOC_7="$TMP_DIR/university-order-001-2026.pdf"
UNIVERSITY_ORDER_DOC_8="$TMP_DIR/university-order-002-2026.pdf"
FINANCIAL_REPORT_DOC_2023="$TMP_DIR/financial-report-2023.pdf"
FINANCIAL_REPORT_DOC_2024="$TMP_DIR/financial-report-2024.pdf"
FINANCIAL_REPORT_DOC_2025="$TMP_DIR/financial-report-2025.pdf"

make_mock_document "$STUDENT_SCHEDULE_DOC_1" "Student schedule PP-101 autumn 2025"
make_mock_document "$STUDENT_SCHEDULE_DOC_2" "Student schedule IT-201 spring 2025"
make_mock_document "$STUDENT_SCHEDULE_DOC_3" "Student schedule HIS-301 autumn 2024"
make_mock_document "$STUDENT_SCHEDULE_DOC_4" "Student schedule MATH-401 spring 2024"
make_mock_document "$EXAM_PROGRAMME_DOC_1" "Exam programme Ukrainian language"
make_mock_document "$EXAM_PROGRAMME_DOC_2" "Exam programme Mathematics"
make_mock_document "$EXAM_PROGRAMME_DOC_3" "Exam programme History"
make_mock_document "$EXAM_PROGRAMME_DOC_4" "Exam programme Pedagogy"
make_mock_document "$EXAM_PROGRAMME_DOC_5" "Exam programme Computer science"
make_mock_document "$EXAM_PROGRAMME_DOC_6" "Exam programme Psychology"
make_mock_document "$UNIVERSITY_ORDER_DOC_1" "University order 001/2024"
make_mock_document "$UNIVERSITY_ORDER_DOC_2" "University order 002/2024"
make_mock_document "$UNIVERSITY_ORDER_DOC_3" "University order 003/2024"
make_mock_document "$UNIVERSITY_ORDER_DOC_4" "University order 001/2025"
make_mock_document "$UNIVERSITY_ORDER_DOC_5" "University order 002/2025"
make_mock_document "$UNIVERSITY_ORDER_DOC_6" "University order 003/2025"
make_mock_document "$UNIVERSITY_ORDER_DOC_7" "University order 001/2026"
make_mock_document "$UNIVERSITY_ORDER_DOC_8" "University order 002/2026"
make_mock_document "$FINANCIAL_REPORT_DOC_2023" "Financial report 2023"
make_mock_document "$FINANCIAL_REPORT_DOC_2024" "Financial report 2024"
make_mock_document "$FINANCIAL_REPORT_DOC_2025" "Financial report 2025"

log "Ensuring file uploads..."
GALLERY_IMAGE_1_ID=$(ensure_file "gallery-campus-a.png" "$GALLERY_IMAGE_1")
GALLERY_IMAGE_2_ID=$(ensure_file "gallery-campus-b.png" "$GALLERY_IMAGE_2")
MEMORIAL_IMAGE_1_ID=$(ensure_file "memorial-entry-a.png" "$MEMORIAL_IMAGE_1")
MEMORIAL_IMAGE_2_ID=$(ensure_file "memorial-entry-b.png" "$MEMORIAL_IMAGE_2")
STUDENT_SCHEDULE_DOC_1_ID=$(ensure_file "student-schedule-pp101-autumn-2025.pdf" "$STUDENT_SCHEDULE_DOC_1")
STUDENT_SCHEDULE_DOC_2_ID=$(ensure_file "student-schedule-it201-spring-2025.pdf" "$STUDENT_SCHEDULE_DOC_2")
STUDENT_SCHEDULE_DOC_3_ID=$(ensure_file "student-schedule-his301-autumn-2024.pdf" "$STUDENT_SCHEDULE_DOC_3")
STUDENT_SCHEDULE_DOC_4_ID=$(ensure_file "student-schedule-math401-spring-2024.pdf" "$STUDENT_SCHEDULE_DOC_4")
EXAM_PROGRAMME_DOC_1_ID=$(ensure_file "exam-program-ukrainian-language.pdf" "$EXAM_PROGRAMME_DOC_1")
EXAM_PROGRAMME_DOC_2_ID=$(ensure_file "exam-program-mathematics.pdf" "$EXAM_PROGRAMME_DOC_2")
EXAM_PROGRAMME_DOC_3_ID=$(ensure_file "exam-program-history.pdf" "$EXAM_PROGRAMME_DOC_3")
EXAM_PROGRAMME_DOC_4_ID=$(ensure_file "exam-program-pedagogy.pdf" "$EXAM_PROGRAMME_DOC_4")
EXAM_PROGRAMME_DOC_5_ID=$(ensure_file "exam-program-computer-science.pdf" "$EXAM_PROGRAMME_DOC_5")
EXAM_PROGRAMME_DOC_6_ID=$(ensure_file "exam-program-psychology.pdf" "$EXAM_PROGRAMME_DOC_6")
UNIVERSITY_ORDER_DOC_1_ID=$(ensure_file "university-order-001-2024.pdf" "$UNIVERSITY_ORDER_DOC_1")
UNIVERSITY_ORDER_DOC_2_ID=$(ensure_file "university-order-002-2024.pdf" "$UNIVERSITY_ORDER_DOC_2")
UNIVERSITY_ORDER_DOC_3_ID=$(ensure_file "university-order-003-2024.pdf" "$UNIVERSITY_ORDER_DOC_3")
UNIVERSITY_ORDER_DOC_4_ID=$(ensure_file "university-order-001-2025.pdf" "$UNIVERSITY_ORDER_DOC_4")
UNIVERSITY_ORDER_DOC_5_ID=$(ensure_file "university-order-002-2025.pdf" "$UNIVERSITY_ORDER_DOC_5")
UNIVERSITY_ORDER_DOC_6_ID=$(ensure_file "university-order-003-2025.pdf" "$UNIVERSITY_ORDER_DOC_6")
UNIVERSITY_ORDER_DOC_7_ID=$(ensure_file "university-order-001-2026.pdf" "$UNIVERSITY_ORDER_DOC_7")
UNIVERSITY_ORDER_DOC_8_ID=$(ensure_file "university-order-002-2026.pdf" "$UNIVERSITY_ORDER_DOC_8")
FINANCIAL_REPORT_DOC_2023_ID=$(ensure_file "financial-report-2023.pdf" "$FINANCIAL_REPORT_DOC_2023")
FINANCIAL_REPORT_DOC_2024_ID=$(ensure_file "financial-report-2024.pdf" "$FINANCIAL_REPORT_DOC_2024")
FINANCIAL_REPORT_DOC_2025_ID=$(ensure_file "financial-report-2025.pdf" "$FINANCIAL_REPORT_DOC_2025")

log "Upserting gallery categories..."
CAT_CAMPUS_ID=$(upsert_single "gallery_categories" \
  "/items/gallery_categories?filter%5Bslug%5D%5B_eq%5D=campus-life&fields=id,slug&limit=1" \
  '{"status":"published","name":"Кампус","nameEn":"Campus","slug":"campus-life","order":1}' \
  '{"status":"published","name":"Кампус","nameEn":"Campus","order":1}')

CAT_EVENTS_ID=$(upsert_single "gallery_categories" \
  "/items/gallery_categories?filter%5Bslug%5D%5B_eq%5D=university-events&fields=id,slug&limit=1" \
  '{"status":"published","name":"Події","nameEn":"Events","slug":"university-events","order":2}' \
  '{"status":"published","name":"Події","nameEn":"Events","order":2}')

log "Upserting gallery items..."
upsert_single "gallery_items" \
  "/items/gallery_items?filter%5Bcategory%5D%5B_eq%5D=$CAT_CAMPUS_ID&filter%5Border%5D%5B_eq%5D=1&fields=id&limit=1" \
  "{\"status\":\"published\",\"title\":\"Головний корпус\",\"titleEn\":\"Main building\",\"image\":\"$GALLERY_IMAGE_1_ID\",\"category\":\"$CAT_CAMPUS_ID\",\"order\":1,\"colSpan\":2,\"rowSpan\":1}" \
  "{\"status\":\"published\",\"title\":\"Головний корпус\",\"titleEn\":\"Main building\",\"image\":\"$GALLERY_IMAGE_1_ID\",\"category\":\"$CAT_CAMPUS_ID\",\"order\":1,\"colSpan\":2,\"rowSpan\":1}" \
  >/dev/null

upsert_single "gallery_items" \
  "/items/gallery_items?filter%5Bcategory%5D%5B_eq%5D=$CAT_EVENTS_ID&filter%5Border%5D%5B_eq%5D=1&fields=id&limit=1" \
  "{\"status\":\"published\",\"title\":\"Студентський форум\",\"titleEn\":\"Student forum\",\"image\":\"$GALLERY_IMAGE_2_ID\",\"category\":\"$CAT_EVENTS_ID\",\"order\":1,\"colSpan\":1,\"rowSpan\":1}" \
  "{\"status\":\"published\",\"title\":\"Студентський форум\",\"titleEn\":\"Student forum\",\"image\":\"$GALLERY_IMAGE_2_ID\",\"category\":\"$CAT_EVENTS_ID\",\"order\":1,\"colSpan\":1,\"rowSpan\":1}" \
  >/dev/null

log "Upserting memorial entries..."
upsert_single "memorial_entries" \
  "/items/memorial_entries?filter%5Border%5D%5B_eq%5D=1&fields=id&limit=1" \
  "{\"status\":\"published\",\"name\":\"Герой А\",\"nameEn\":\"Hero A\",\"role\":\"Випускник\",\"roleEn\":\"Alumnus\",\"photo\":\"$MEMORIAL_IMAGE_1_ID\",\"order\":1}" \
  "{\"status\":\"published\",\"nameEn\":\"Hero A\",\"role\":\"Випускник\",\"roleEn\":\"Alumnus\",\"photo\":\"$MEMORIAL_IMAGE_1_ID\",\"order\":1}" \
  >/dev/null

upsert_single "memorial_entries" \
  "/items/memorial_entries?filter%5Border%5D%5B_eq%5D=2&fields=id&limit=1" \
  "{\"status\":\"published\",\"name\":\"Герой Б\",\"nameEn\":\"Hero B\",\"role\":\"Захисник України\",\"roleEn\":\"Defender of Ukraine\",\"photo\":\"$MEMORIAL_IMAGE_2_ID\",\"order\":2}" \
  "{\"status\":\"published\",\"nameEn\":\"Hero B\",\"role\":\"Захисник України\",\"roleEn\":\"Defender of Ukraine\",\"photo\":\"$MEMORIAL_IMAGE_2_ID\",\"order\":2}" \
  >/dev/null

log "Upserting faculties..."
FAC_PED_ID=$(upsert_single "faculties" \
  "/items/faculties?filter%5Bslug%5D%5B_eq%5D=pedagogy-and-psychology&fields=id,slug&limit=1" \
  '{"status":"published","name":"Факультет педагогіки та психології","nameEn":"Faculty of Pedagogy and Psychology","slug":"pedagogy-and-psychology","dean":"проф. Олена Коваль","deanEn":"Prof. Olena Koval","departmentsCount":3,"studentsCount":850,"order":1}' \
  '{"status":"published","name":"Факультет педагогіки та психології","nameEn":"Faculty of Pedagogy and Psychology","dean":"проф. Олена Коваль","deanEn":"Prof. Olena Koval","departmentsCount":3,"studentsCount":850,"order":1}')

FAC_IT_ID=$(upsert_single "faculties" \
  "/items/faculties?filter%5Bslug%5D%5B_eq%5D=information-technologies&fields=id,slug&limit=1" \
  '{"status":"published","name":"Факультет інформаційних технологій","nameEn":"Faculty of Information Technologies","slug":"information-technologies","dean":"доц. Ігор Мельник","deanEn":"Assoc. Prof. Ihor Melnyk","departmentsCount":2,"studentsCount":620,"order":2}' \
  '{"status":"published","name":"Факультет інформаційних технологій","nameEn":"Faculty of Information Technologies","dean":"доц. Ігор Мельник","deanEn":"Assoc. Prof. Ihor Melnyk","departmentsCount":2,"studentsCount":620,"order":2}')

log "Upserting faculty departments..."
upsert_single "faculty_departments" \
  "/items/faculty_departments?filter%5Bfaculty%5D%5B_eq%5D=$FAC_PED_ID&filter%5Border%5D%5B_eq%5D=1&fields=id&limit=1" \
  "{\"faculty\":\"$FAC_PED_ID\",\"name\":\"Кафедра педагогіки\",\"nameEn\":\"Department of Pedagogy\",\"order\":1}" \
  "{\"faculty\":\"$FAC_PED_ID\",\"nameEn\":\"Department of Pedagogy\",\"order\":1}" \
  >/dev/null

upsert_single "faculty_departments" \
  "/items/faculty_departments?filter%5Bfaculty%5D%5B_eq%5D=$FAC_IT_ID&filter%5Border%5D%5B_eq%5D=1&fields=id&limit=1" \
  "{\"faculty\":\"$FAC_IT_ID\",\"name\":\"Кафедра програмної інженерії\",\"nameEn\":\"Department of Software Engineering\",\"order\":1}" \
  "{\"faculty\":\"$FAC_IT_ID\",\"nameEn\":\"Department of Software Engineering\",\"order\":1}" \
  >/dev/null

log "Upserting vacancies..."
upsert_single "vacancies" \
  "/items/vacancies?filter%5Bcompany%5D%5B_eq%5D=SoftServe&filter%5Bposition%5D%5B_eq%5D=Junior%20Frontend%20Developer&fields=id&limit=1" \
  '{"status":"published","company":"SoftServe","companyEn":"SoftServe","position":"Junior Frontend Developer","positionEn":"Junior Frontend Developer","type":"fullTime","location":"Львів","locationEn":"Lviv","postedAt":"2026-03-15T09:00:00.000Z","order":1}' \
  '{"status":"published","companyEn":"SoftServe","positionEn":"Junior Frontend Developer","type":"fullTime","location":"Львів","locationEn":"Lviv","postedAt":"2026-03-15T09:00:00.000Z","order":1}' \
  >/dev/null

upsert_single "vacancies" \
  "/items/vacancies?filter%5Bcompany%5D%5B_eq%5D=EPAM&filter%5Bposition%5D%5B_eq%5D=QA%20Intern&fields=id&limit=1" \
  '{"status":"published","company":"EPAM","companyEn":"EPAM","position":"QA Intern","positionEn":"QA Intern","type":"internship","location":"Київ","locationEn":"Kyiv","postedAt":"2026-03-20T09:00:00.000Z","order":2}' \
  '{"status":"published","companyEn":"EPAM","positionEn":"QA Intern","type":"internship","location":"Київ","locationEn":"Kyiv","postedAt":"2026-03-20T09:00:00.000Z","order":2}' \
  >/dev/null

log "Upserting baseline categories..."
CAT_UNIVERSITY_ID=$(upsert_single "categories" \
  "/items/categories?filter%5Bslug%5D%5B_eq%5D=university-news&fields=id,slug&limit=1" \
  '{"name":"Новини університету","nameEn":"University news","slug":"university-news"}' \
  '{"name":"Новини університету","nameEn":"University news"}')

CAT_SCIENCE_ID=$(upsert_single "categories" \
  "/items/categories?filter%5Bslug%5D%5B_eq%5D=science-and-research&fields=id,slug&limit=1" \
  '{"name":"Наука і дослідження","nameEn":"Science and research","slug":"science-and-research"}' \
  '{"name":"Наука і дослідження","nameEn":"Science and research"}')

log "Upserting news articles..."
NEWS_COVER_ID=$(ensure_file "news-cover-a.png" "$GALLERY_IMAGE_1")
upsert_single "articles" \
  "/items/articles?filter%5Bslug%5D%5B_eq%5D=open-day-2026&fields=id,slug&limit=1" \
  "{\"status\":\"published\",\"title\":\"День відкритих дверей 2026\",\"titleEn\":\"Open Day 2026\",\"slug\":\"open-day-2026\",\"excerpt\":\"Запрошуємо абітурієнтів на презентацію освітніх програм.\",\"excerptEn\":\"Join our presentation of academic programmes.\",\"content\":\"## День відкритих дверей\\n\\nПриходьте познайомитися з викладачами та кампусом.\",\"contentEn\":\"## Open Day\\n\\nMeet faculty members and explore our campus.\",\"author\":\"Пресслужба\",\"category\":\"$CAT_UNIVERSITY_ID\",\"cover\":\"$NEWS_COVER_ID\",\"date_published\":\"2026-04-10T09:00:00.000Z\"}" \
  "{\"status\":\"published\",\"title\":\"День відкритих дверей 2026\",\"titleEn\":\"Open Day 2026\",\"excerpt\":\"Запрошуємо абітурієнтів на презентацію освітніх програм.\",\"excerptEn\":\"Join our presentation of academic programmes.\",\"content\":\"## День відкритих дверей\\n\\nПриходьте познайомитися з викладачами та кампусом.\",\"contentEn\":\"## Open Day\\n\\nMeet faculty members and explore our campus.\",\"author\":\"Пресслужба\",\"category\":\"$CAT_UNIVERSITY_ID\",\"cover\":\"$NEWS_COVER_ID\",\"date_published\":\"2026-04-10T09:00:00.000Z\"}" \
  >/dev/null

upsert_single "articles" \
  "/items/articles?filter%5Bslug%5D%5B_eq%5D=student-research-grants&fields=id,slug&limit=1" \
  "{\"status\":\"published\",\"title\":\"Гранти для студентських досліджень\",\"titleEn\":\"Student Research Grants\",\"slug\":\"student-research-grants\",\"excerpt\":\"Оголошено конкурс мінігрантів для молодих дослідників.\",\"excerptEn\":\"Mini-grant competition announced for young researchers.\",\"content\":\"## Конкурс грантів\\n\\nПодати заявку можна до 15 травня.\",\"contentEn\":\"## Grant Competition\\n\\nApplications are open until May 15.\",\"author\":\"Науковий відділ\",\"category\":\"$CAT_SCIENCE_ID\",\"cover\":\"$NEWS_COVER_ID\",\"date_published\":\"2026-04-15T09:00:00.000Z\"}" \
  "{\"status\":\"published\",\"title\":\"Гранти для студентських досліджень\",\"titleEn\":\"Student Research Grants\",\"excerpt\":\"Оголошено конкурс мінігрантів для молодих дослідників.\",\"excerptEn\":\"Mini-grant competition announced for young researchers.\",\"content\":\"## Конкурс грантів\\n\\nПодати заявку можна до 15 травня.\",\"contentEn\":\"## Grant Competition\\n\\nApplications are open until May 15.\",\"author\":\"Науковий відділ\",\"category\":\"$CAT_SCIENCE_ID\",\"cover\":\"$NEWS_COVER_ID\",\"date_published\":\"2026-04-15T09:00:00.000Z\"}" \
  >/dev/null

log "Upserting partners..."
PARTNER_LOGO_ID=$(ensure_file "partner-logo-a.png" "$GALLERY_IMAGE_2")
upsert_single "partners" \
  "/items/partners?filter%5Bslug%5D%5B_eq%5D=softserve&fields=id,slug&limit=1" \
  "{\"status\":\"published\",\"name\":\"SoftServe\",\"nameEn\":\"SoftServe\",\"slug\":\"softserve\",\"description\":\"ІТ-партнер університету у сфері стажувань.\",\"descriptionEn\":\"IT partner supporting internship programs.\",\"website\":\"https://www.softserveinc.com\",\"country\":\"Україна\",\"countryEn\":\"Ukraine\",\"logo\":\"$PARTNER_LOGO_ID\"}" \
  "{\"status\":\"published\",\"name\":\"SoftServe\",\"nameEn\":\"SoftServe\",\"description\":\"ІТ-партнер університету у сфері стажувань.\",\"descriptionEn\":\"IT partner supporting internship programs.\",\"website\":\"https://www.softserveinc.com\",\"country\":\"Україна\",\"countryEn\":\"Ukraine\",\"logo\":\"$PARTNER_LOGO_ID\"}" \
  >/dev/null

upsert_single "partners" \
  "/items/partners?filter%5Bslug%5D%5B_eq%5D=epam&fields=id,slug&limit=1" \
  "{\"status\":\"published\",\"name\":\"EPAM\",\"nameEn\":\"EPAM\",\"slug\":\"epam\",\"description\":\"Партнер освітніх і кар'єрних ініціатив.\",\"descriptionEn\":\"Partner of educational and career initiatives.\",\"website\":\"https://www.epam.com\",\"country\":\"Україна\",\"countryEn\":\"Ukraine\",\"logo\":\"$PARTNER_LOGO_ID\"}" \
  "{\"status\":\"published\",\"name\":\"EPAM\",\"nameEn\":\"EPAM\",\"description\":\"Партнер освітніх і кар'єрних ініціатив.\",\"descriptionEn\":\"Partner of educational and career initiatives.\",\"website\":\"https://www.epam.com\",\"country\":\"Україна\",\"countryEn\":\"Ukraine\",\"logo\":\"$PARTNER_LOGO_ID\"}" \
  >/dev/null

log "Upserting events..."
EVENT_COVER_ID=$(ensure_file "event-cover-a.png" "$MEMORIAL_IMAGE_1")
upsert_single "events" \
  "/items/events?filter%5Bslug%5D%5B_eq%5D=innovation-week-2026&fields=id,slug&limit=1" \
  "{\"status\":\"published\",\"title\":\"Тиждень інновацій 2026\",\"titleEn\":\"Innovation Week 2026\",\"slug\":\"innovation-week-2026\",\"description\":\"Серія відкритих лекцій та воркшопів.\",\"descriptionEn\":\"A series of open lectures and workshops.\",\"content\":\"## Програма\\n\\n5 днів подій для студентів та викладачів.\",\"contentEn\":\"## Program\\n\\n5 days of events for students and faculty.\",\"date\":\"2026-05-20T10:00:00.000Z\",\"endDate\":\"2026-05-24T17:00:00.000Z\",\"location\":\"Харків\",\"locationEn\":\"Kharkiv\",\"tag\":\"Освіта\",\"tagEn\":\"Education\",\"cover\":\"$EVENT_COVER_ID\"}" \
  "{\"status\":\"published\",\"title\":\"Тиждень інновацій 2026\",\"titleEn\":\"Innovation Week 2026\",\"description\":\"Серія відкритих лекцій та воркшопів.\",\"descriptionEn\":\"A series of open lectures and workshops.\",\"content\":\"## Програма\\n\\n5 днів подій для студентів та викладачів.\",\"contentEn\":\"## Program\\n\\n5 days of events for students and faculty.\",\"date\":\"2026-05-20T10:00:00.000Z\",\"endDate\":\"2026-05-24T17:00:00.000Z\",\"location\":\"Харків\",\"locationEn\":\"Kharkiv\",\"tag\":\"Освіта\",\"tagEn\":\"Education\",\"cover\":\"$EVENT_COVER_ID\"}" \
  >/dev/null

upsert_single "events" \
  "/items/events?filter%5Bslug%5D%5B_eq%5D=career-day-2026&fields=id,slug&limit=1" \
  "{\"status\":\"published\",\"title\":\"Кар'єрний день 2026\",\"titleEn\":\"Career Day 2026\",\"slug\":\"career-day-2026\",\"description\":\"Зустрічі з роботодавцями та HR-експертами.\",\"descriptionEn\":\"Meetings with employers and HR experts.\",\"content\":\"## Що на вас чекає\\n\\nЯрмарок вакансій та консультації.\",\"contentEn\":\"## What to expect\\n\\nJob fair and career consultations.\",\"date\":\"2026-06-01T09:00:00.000Z\",\"endDate\":\"2026-06-01T16:00:00.000Z\",\"location\":\"Харків\",\"locationEn\":\"Kharkiv\",\"tag\":\"Кар'єра\",\"tagEn\":\"Career\",\"cover\":\"$EVENT_COVER_ID\"}" \
  "{\"status\":\"published\",\"title\":\"Кар'єрний день 2026\",\"titleEn\":\"Career Day 2026\",\"description\":\"Зустрічі з роботодавцями та HR-експертами.\",\"descriptionEn\":\"Meetings with employers and HR experts.\",\"content\":\"## Що на вас чекає\\n\\nЯрмарок вакансій та консультації.\",\"contentEn\":\"## What to expect\\n\\nJob fair and career consultations.\",\"date\":\"2026-06-01T09:00:00.000Z\",\"endDate\":\"2026-06-01T16:00:00.000Z\",\"location\":\"Харків\",\"locationEn\":\"Kharkiv\",\"tag\":\"Кар'єра\",\"tagEn\":\"Career\",\"cover\":\"$EVENT_COVER_ID\"}" \
  >/dev/null

log "Upserting programmes (specialities)..."
PROGRAMME_COVER_ID=$(ensure_file "programme-cover-a.png" "$MEMORIAL_IMAGE_2")
upsert_single "programmes" \
  "/items/programmes?filter%5Bslug%5D%5B_eq%5D=computer-science-bachelor&fields=id,slug&limit=1" \
  "{\"status\":\"published\",\"title\":\"Комп'ютерні науки\",\"titleEn\":\"Computer Science\",\"slug\":\"computer-science-bachelor\",\"level\":\"bachelor\",\"faculty\":\"Факультет інформаційних технологій\",\"facultyEn\":\"Faculty of Information Technologies\",\"description\":\"Освітня програма для майбутніх розробників.\",\"descriptionEn\":\"Programme for future software engineers.\",\"content\":\"## Що вивчаємо\\n\\nАлгоритми, веб-розробка, бази даних.\",\"contentEn\":\"## Curriculum\\n\\nAlgorithms, web development, databases.\",\"duration\":\"4 роки\",\"formOfStudy\":\"Денна\",\"cover\":\"$PROGRAMME_COVER_ID\"}" \
  "{\"status\":\"published\",\"title\":\"Комп'ютерні науки\",\"titleEn\":\"Computer Science\",\"description\":\"Освітня програма для майбутніх розробників.\",\"descriptionEn\":\"Programme for future software engineers.\",\"level\":\"bachelor\",\"faculty\":\"Факультет інформаційних технологій\",\"facultyEn\":\"Faculty of Information Technologies\",\"content\":\"## Що вивчаємо\\n\\nАлгоритми, веб-розробка, бази даних.\",\"contentEn\":\"## Curriculum\\n\\nAlgorithms, web development, databases.\",\"duration\":\"4 роки\",\"formOfStudy\":\"Денна\",\"cover\":\"$PROGRAMME_COVER_ID\"}" \
  >/dev/null

upsert_single "programmes" \
  "/items/programmes?filter%5Bslug%5D%5B_eq%5D=educational-psychology-master&fields=id,slug&limit=1" \
  "{\"status\":\"published\",\"title\":\"Психологія освіти\",\"titleEn\":\"Educational Psychology\",\"slug\":\"educational-psychology-master\",\"level\":\"master\",\"faculty\":\"Факультет педагогіки та психології\",\"facultyEn\":\"Faculty of Pedagogy and Psychology\",\"description\":\"Програма для підготовки психологів освітнього середовища.\",\"descriptionEn\":\"Programme for educational environment psychologists.\",\"content\":\"## Напрями\\n\\nПсиходіагностика, консультування, супервізія.\",\"contentEn\":\"## Focus areas\\n\\nPsychodiagnostics, counseling, supervision.\",\"duration\":\"1.5 роки\",\"formOfStudy\":\"Денна\",\"cover\":\"$PROGRAMME_COVER_ID\"}" \
  "{\"status\":\"published\",\"title\":\"Психологія освіти\",\"titleEn\":\"Educational Psychology\",\"description\":\"Програма для підготовки психологів освітнього середовища.\",\"descriptionEn\":\"Programme for educational environment psychologists.\",\"level\":\"master\",\"faculty\":\"Факультет педагогіки та психології\",\"facultyEn\":\"Faculty of Pedagogy and Psychology\",\"content\":\"## Напрями\\n\\nПсиходіагностика, консультування, супервізія.\",\"contentEn\":\"## Focus areas\\n\\nPsychodiagnostics, counseling, supervision.\",\"duration\":\"1.5 роки\",\"formOfStudy\":\"Денна\",\"cover\":\"$PROGRAMME_COVER_ID\"}" \
  >/dev/null

log "Upserting student schedule documents..."
upsert_single "student_schedule_documents" \
  "/items/student_schedule_documents?filter%5BgroupCode%5D%5B_eq%5D=PP-101&filter%5Bsemester%5D%5B_eq%5D=autumn&filter%5BacademicYear%5D%5B_eq%5D=2025-2026&fields=id&limit=1" \
  "{\"status\":\"published\",\"title\":\"Розклад занять PP-101\",\"titleEn\":\"Class schedule PP-101\",\"faculty\":\"Факультет педагогіки та психології\",\"facultyEn\":\"Faculty of Pedagogy and Psychology\",\"groupCode\":\"PP-101\",\"semester\":\"autumn\",\"academicYear\":\"2025-2026\",\"validFrom\":\"2025-09-01\",\"validTo\":\"2025-12-31\",\"file\":\"$STUDENT_SCHEDULE_DOC_1_ID\",\"order\":1}" \
  "{\"status\":\"published\",\"title\":\"Розклад занять PP-101\",\"titleEn\":\"Class schedule PP-101\",\"faculty\":\"Факультет педагогіки та психології\",\"facultyEn\":\"Faculty of Pedagogy and Psychology\",\"validFrom\":\"2025-09-01\",\"validTo\":\"2025-12-31\",\"file\":\"$STUDENT_SCHEDULE_DOC_1_ID\",\"order\":1}" \
  >/dev/null

upsert_single "student_schedule_documents" \
  "/items/student_schedule_documents?filter%5BgroupCode%5D%5B_eq%5D=IT-201&filter%5Bsemester%5D%5B_eq%5D=spring&filter%5BacademicYear%5D%5B_eq%5D=2024-2025&fields=id&limit=1" \
  "{\"status\":\"published\",\"title\":\"Розклад занять IT-201\",\"titleEn\":\"Class schedule IT-201\",\"faculty\":\"Факультет інформаційних технологій\",\"facultyEn\":\"Faculty of Information Technologies\",\"groupCode\":\"IT-201\",\"semester\":\"spring\",\"academicYear\":\"2024-2025\",\"validFrom\":\"2025-02-10\",\"validTo\":\"2025-06-20\",\"file\":\"$STUDENT_SCHEDULE_DOC_2_ID\",\"order\":2}" \
  "{\"status\":\"published\",\"title\":\"Розклад занять IT-201\",\"titleEn\":\"Class schedule IT-201\",\"faculty\":\"Факультет інформаційних технологій\",\"facultyEn\":\"Faculty of Information Technologies\",\"validFrom\":\"2025-02-10\",\"validTo\":\"2025-06-20\",\"file\":\"$STUDENT_SCHEDULE_DOC_2_ID\",\"order\":2}" \
  >/dev/null

upsert_single "student_schedule_documents" \
  "/items/student_schedule_documents?filter%5BgroupCode%5D%5B_eq%5D=HIS-301&filter%5Bsemester%5D%5B_eq%5D=autumn&filter%5BacademicYear%5D%5B_eq%5D=2024-2025&fields=id&limit=1" \
  "{\"status\":\"published\",\"title\":\"Розклад занять HIS-301\",\"titleEn\":\"Class schedule HIS-301\",\"faculty\":\"Історичний факультет\",\"facultyEn\":\"Faculty of History\",\"groupCode\":\"HIS-301\",\"semester\":\"autumn\",\"academicYear\":\"2024-2025\",\"validFrom\":\"2024-09-02\",\"validTo\":\"2024-12-29\",\"file\":\"$STUDENT_SCHEDULE_DOC_3_ID\",\"order\":3}" \
  "{\"status\":\"published\",\"title\":\"Розклад занять HIS-301\",\"titleEn\":\"Class schedule HIS-301\",\"faculty\":\"Історичний факультет\",\"facultyEn\":\"Faculty of History\",\"validFrom\":\"2024-09-02\",\"validTo\":\"2024-12-29\",\"file\":\"$STUDENT_SCHEDULE_DOC_3_ID\",\"order\":3}" \
  >/dev/null

upsert_single "student_schedule_documents" \
  "/items/student_schedule_documents?filter%5BgroupCode%5D%5B_eq%5D=MATH-401&filter%5Bsemester%5D%5B_eq%5D=spring&filter%5BacademicYear%5D%5B_eq%5D=2023-2024&fields=id&limit=1" \
  "{\"status\":\"published\",\"title\":\"Розклад занять MATH-401\",\"titleEn\":\"Class schedule MATH-401\",\"faculty\":\"Фізико-математичний факультет\",\"facultyEn\":\"Faculty of Physics and Mathematics\",\"groupCode\":\"MATH-401\",\"semester\":\"spring\",\"academicYear\":\"2023-2024\",\"validFrom\":\"2024-02-05\",\"validTo\":\"2024-06-15\",\"file\":\"$STUDENT_SCHEDULE_DOC_4_ID\",\"order\":4}" \
  "{\"status\":\"published\",\"title\":\"Розклад занять MATH-401\",\"titleEn\":\"Class schedule MATH-401\",\"faculty\":\"Фізико-математичний факультет\",\"facultyEn\":\"Faculty of Physics and Mathematics\",\"validFrom\":\"2024-02-05\",\"validTo\":\"2024-06-15\",\"file\":\"$STUDENT_SCHEDULE_DOC_4_ID\",\"order\":4}" \
  >/dev/null

log "Upserting education schedule periods..."
upsert_single "education_schedule_periods" \
  "/items/education_schedule_periods?filter%5BacademicYear%5D%5B_eq%5D=2025-2026&filter%5Border%5D%5B_eq%5D=1&fields=id&limit=1" \
  '{"status":"published","name":"Осінній навчальний семестр","nameEn":"Autumn study semester","semesterType":"autumn","periodType":"study","dateStart":"2025-09-01","dateEnd":"2025-12-20","academicYear":"2025-2026","order":1}' \
  '{"status":"published","name":"Осінній навчальний семестр","nameEn":"Autumn study semester","semesterType":"autumn","periodType":"study","dateStart":"2025-09-01","dateEnd":"2025-12-20"}' \
  >/dev/null

upsert_single "education_schedule_periods" \
  "/items/education_schedule_periods?filter%5BacademicYear%5D%5B_eq%5D=2025-2026&filter%5Border%5D%5B_eq%5D=2&fields=id&limit=1" \
  '{"status":"published","name":"Зимова екзаменаційна сесія","nameEn":"Winter exam session","semesterType":"autumn","periodType":"exam","dateStart":"2025-12-22","dateEnd":"2026-01-10","academicYear":"2025-2026","order":2}' \
  '{"status":"published","name":"Зимова екзаменаційна сесія","nameEn":"Winter exam session","semesterType":"autumn","periodType":"exam","dateStart":"2025-12-22","dateEnd":"2026-01-10"}' \
  >/dev/null

upsert_single "education_schedule_periods" \
  "/items/education_schedule_periods?filter%5BacademicYear%5D%5B_eq%5D=2025-2026&filter%5Border%5D%5B_eq%5D=3&fields=id&limit=1" \
  '{"status":"published","name":"Зимові канікули","nameEn":"Winter vacation","semesterType":"spring","periodType":"vacation","dateStart":"2026-01-11","dateEnd":"2026-01-31","academicYear":"2025-2026","order":3}' \
  '{"status":"published","name":"Зимові канікули","nameEn":"Winter vacation","semesterType":"spring","periodType":"vacation","dateStart":"2026-01-11","dateEnd":"2026-01-31"}' \
  >/dev/null

upsert_single "education_schedule_periods" \
  "/items/education_schedule_periods?filter%5BacademicYear%5D%5B_eq%5D=2025-2026&filter%5Border%5D%5B_eq%5D=4&fields=id&limit=1" \
  '{"status":"published","name":"Весняний навчальний семестр","nameEn":"Spring study semester","semesterType":"spring","periodType":"study","dateStart":"2026-02-02","dateEnd":"2026-05-25","academicYear":"2025-2026","order":4}' \
  '{"status":"published","name":"Весняний навчальний семестр","nameEn":"Spring study semester","semesterType":"spring","periodType":"study","dateStart":"2026-02-02","dateEnd":"2026-05-25"}' \
  >/dev/null

upsert_single "education_schedule_periods" \
  "/items/education_schedule_periods?filter%5BacademicYear%5D%5B_eq%5D=2025-2026&filter%5Border%5D%5B_eq%5D=5&fields=id&limit=1" \
  '{"status":"published","name":"Літня екзаменаційна сесія","nameEn":"Summer exam session","semesterType":"spring","periodType":"exam","dateStart":"2026-05-26","dateEnd":"2026-06-15","academicYear":"2025-2026","order":5}' \
  '{"status":"published","name":"Літня екзаменаційна сесія","nameEn":"Summer exam session","semesterType":"spring","periodType":"exam","dateStart":"2026-05-26","dateEnd":"2026-06-15"}' \
  >/dev/null

upsert_single "education_schedule_periods" \
  "/items/education_schedule_periods?filter%5BacademicYear%5D%5B_eq%5D=2025-2026&filter%5Border%5D%5B_eq%5D=6&fields=id&limit=1" \
  '{"status":"published","name":"Виробнича практика","nameEn":"Internship period","semesterType":"spring","periodType":"internship","dateStart":"2026-06-16","dateEnd":"2026-07-10","academicYear":"2025-2026","order":6}' \
  '{"status":"published","name":"Виробнича практика","nameEn":"Internship period","semesterType":"spring","periodType":"internship","dateStart":"2026-06-16","dateEnd":"2026-07-10"}' \
  >/dev/null

log "Upserting education schedule key dates..."
upsert_single "education_schedule_key_dates" \
  "/items/education_schedule_key_dates?filter%5BacademicYear%5D%5B_eq%5D=2025-2026&filter%5Border%5D%5B_eq%5D=1&fields=id&limit=1" \
  '{"status":"published","event":"Початок навчального року","eventEn":"Academic year start","dateLabel":"1 вересня 2025","dateLabelEn":"September 1, 2025","academicYear":"2025-2026","order":1}' \
  '{"status":"published","event":"Початок навчального року","eventEn":"Academic year start","dateLabel":"1 вересня 2025","dateLabelEn":"September 1, 2025"}' \
  >/dev/null

upsert_single "education_schedule_key_dates" \
  "/items/education_schedule_key_dates?filter%5BacademicYear%5D%5B_eq%5D=2025-2026&filter%5Border%5D%5B_eq%5D=2&fields=id&limit=1" \
  '{"status":"published","event":"День першокурсника","eventEn":"Freshers day","dateLabel":"5 вересня 2025","dateLabelEn":"September 5, 2025","academicYear":"2025-2026","order":2}' \
  '{"status":"published","event":"День першокурсника","eventEn":"Freshers day","dateLabel":"5 вересня 2025","dateLabelEn":"September 5, 2025"}' \
  >/dev/null

upsert_single "education_schedule_key_dates" \
  "/items/education_schedule_key_dates?filter%5BacademicYear%5D%5B_eq%5D=2025-2026&filter%5Border%5D%5B_eq%5D=3&fields=id&limit=1" \
  '{"status":"published","event":"Початок зимової сесії","eventEn":"Winter session start","dateLabel":"22 грудня 2025","dateLabelEn":"December 22, 2025","academicYear":"2025-2026","order":3}' \
  '{"status":"published","event":"Початок зимової сесії","eventEn":"Winter session start","dateLabel":"22 грудня 2025","dateLabelEn":"December 22, 2025"}' \
  >/dev/null

upsert_single "education_schedule_key_dates" \
  "/items/education_schedule_key_dates?filter%5BacademicYear%5D%5B_eq%5D=2025-2026&filter%5Border%5D%5B_eq%5D=4&fields=id&limit=1" \
  '{"status":"published","event":"Початок весняного семестру","eventEn":"Spring semester start","dateLabel":"2 лютого 2026","dateLabelEn":"February 2, 2026","academicYear":"2025-2026","order":4}' \
  '{"status":"published","event":"Початок весняного семестру","eventEn":"Spring semester start","dateLabel":"2 лютого 2026","dateLabelEn":"February 2, 2026"}' \
  >/dev/null

upsert_single "education_schedule_key_dates" \
  "/items/education_schedule_key_dates?filter%5BacademicYear%5D%5B_eq%5D=2025-2026&filter%5Border%5D%5B_eq%5D=5&fields=id&limit=1" \
  '{"status":"published","event":"Початок літньої сесії","eventEn":"Summer session start","dateLabel":"26 травня 2026","dateLabelEn":"May 26, 2026","academicYear":"2025-2026","order":5}' \
  '{"status":"published","event":"Початок літньої сесії","eventEn":"Summer session start","dateLabel":"26 травня 2026","dateLabelEn":"May 26, 2026"}' \
  >/dev/null

upsert_single "education_schedule_key_dates" \
  "/items/education_schedule_key_dates?filter%5BacademicYear%5D%5B_eq%5D=2025-2026&filter%5Border%5D%5B_eq%5D=6&fields=id&limit=1" \
  '{"status":"published","event":"Вручення дипломів","eventEn":"Graduation ceremony","dateLabel":"30 червня 2026","dateLabelEn":"June 30, 2026","academicYear":"2025-2026","order":6}' \
  '{"status":"published","event":"Вручення дипломів","eventEn":"Graduation ceremony","dateLabel":"30 червня 2026","dateLabelEn":"June 30, 2026"}' \
  >/dev/null

log "Upserting admission open days..."
upsert_single "admission_open_days" \
  "/items/admission_open_days?filter%5BeventDate%5D%5B_eq%5D=2026-05-10T10:00:00.000Z&fields=id&limit=1" \
  '{"status":"published","title":"Весняний день відкритих дверей","titleEn":"Spring Open Day","description":"Презентація факультетів і спеціальностей.","descriptionEn":"Presentation of faculties and programmes.","eventDate":"2026-05-10T10:00:00.000Z","location":"Головний корпус, актова зала","locationEn":"Main building, assembly hall","registrationUrl":"https://example.edu/open-day-spring-2026","order":1}' \
  '{"status":"published","title":"Весняний день відкритих дверей","titleEn":"Spring Open Day","description":"Презентація факультетів і спеціальностей.","descriptionEn":"Presentation of faculties and programmes.","location":"Головний корпус, актова зала","locationEn":"Main building, assembly hall","registrationUrl":"https://example.edu/open-day-spring-2026"}' \
  >/dev/null

upsert_single "admission_open_days" \
  "/items/admission_open_days?filter%5BeventDate%5D%5B_eq%5D=2026-06-14T10:00:00.000Z&fields=id&limit=1" \
  '{"status":"published","title":"Літній день абітурієнта","titleEn":"Summer Applicant Day","description":"Консультації приймальної комісії та екскурсія кампусом.","descriptionEn":"Admissions consultations and campus tour.","eventDate":"2026-06-14T10:00:00.000Z","location":"Центр студентських сервісів","locationEn":"Student Services Center","registrationUrl":"https://example.edu/open-day-summer-2026","order":2}' \
  '{"status":"published","title":"Літній день абітурієнта","titleEn":"Summer Applicant Day","description":"Консультації приймальної комісії та екскурсія кампусом.","descriptionEn":"Admissions consultations and campus tour.","location":"Центр студентських сервісів","locationEn":"Student Services Center","registrationUrl":"https://example.edu/open-day-summer-2026"}' \
  >/dev/null

upsert_single "admission_open_days" \
  "/items/admission_open_days?filter%5BeventDate%5D%5B_eq%5D=2026-11-22T10:00:00.000Z&fields=id&limit=1" \
  '{"status":"published","title":"Осінній день відкритих дверей","titleEn":"Autumn Open Day","description":"Зустріч з деканами, викладачами та студентами.","descriptionEn":"Meet deans, faculty, and students.","eventDate":"2026-11-22T10:00:00.000Z","location":"Навчально-бібліотечний корпус","locationEn":"Academic library building","registrationUrl":"https://example.edu/open-day-autumn-2026","order":3}' \
  '{"status":"published","title":"Осінній день відкритих дверей","titleEn":"Autumn Open Day","description":"Зустріч з деканами, викладачами та студентами.","descriptionEn":"Meet deans, faculty, and students.","location":"Навчально-бібліотечний корпус","locationEn":"Academic library building","registrationUrl":"https://example.edu/open-day-autumn-2026"}' \
  >/dev/null

log "Upserting admission exam programs..."
upsert_single "admission_exam_programs" \
  "/items/admission_exam_programs?filter%5Bsubject%5D%5B_eq%5D=Українська%20мова&filter%5Blevel%5D%5B_eq%5D=bachelor&fields=id&limit=1" \
  "{\"status\":\"published\",\"subject\":\"Українська мова\",\"subjectEn\":\"Ukrainian language\",\"level\":\"bachelor\",\"description\":\"Програма фахового вступного випробування.\",\"descriptionEn\":\"Programme for bachelor entry examination.\",\"programmeFile\":\"$EXAM_PROGRAMME_DOC_1_ID\",\"order\":1}" \
  "{\"status\":\"published\",\"subjectEn\":\"Ukrainian language\",\"description\":\"Програма фахового вступного випробування.\",\"descriptionEn\":\"Programme for bachelor entry examination.\",\"programmeFile\":\"$EXAM_PROGRAMME_DOC_1_ID\",\"order\":1}" \
  >/dev/null

upsert_single "admission_exam_programs" \
  "/items/admission_exam_programs?filter%5Bsubject%5D%5B_eq%5D=Математика&filter%5Blevel%5D%5B_eq%5D=bachelor&fields=id&limit=1" \
  "{\"status\":\"published\",\"subject\":\"Математика\",\"subjectEn\":\"Mathematics\",\"level\":\"bachelor\",\"description\":\"Програма для вступу на технічні спеціальності.\",\"descriptionEn\":\"Programme for technical programme applicants.\",\"programmeFile\":\"$EXAM_PROGRAMME_DOC_2_ID\",\"order\":2}" \
  "{\"status\":\"published\",\"subjectEn\":\"Mathematics\",\"description\":\"Програма для вступу на технічні спеціальності.\",\"descriptionEn\":\"Programme for technical programme applicants.\",\"programmeFile\":\"$EXAM_PROGRAMME_DOC_2_ID\",\"order\":2}" \
  >/dev/null

upsert_single "admission_exam_programs" \
  "/items/admission_exam_programs?filter%5Bsubject%5D%5B_eq%5D=Історія%20України&filter%5Blevel%5D%5B_eq%5D=bachelor&fields=id&limit=1" \
  "{\"status\":\"published\",\"subject\":\"Історія України\",\"subjectEn\":\"History of Ukraine\",\"level\":\"bachelor\",\"description\":\"Програма для гуманітарних спеціальностей.\",\"descriptionEn\":\"Programme for humanities applicants.\",\"programmeFile\":\"$EXAM_PROGRAMME_DOC_3_ID\",\"order\":3}" \
  "{\"status\":\"published\",\"subjectEn\":\"History of Ukraine\",\"description\":\"Програма для гуманітарних спеціальностей.\",\"descriptionEn\":\"Programme for humanities applicants.\",\"programmeFile\":\"$EXAM_PROGRAMME_DOC_3_ID\",\"order\":3}" \
  >/dev/null

upsert_single "admission_exam_programs" \
  "/items/admission_exam_programs?filter%5Bsubject%5D%5B_eq%5D=Педагогіка&filter%5Blevel%5D%5B_eq%5D=master&fields=id&limit=1" \
  "{\"status\":\"published\",\"subject\":\"Педагогіка\",\"subjectEn\":\"Pedagogy\",\"level\":\"master\",\"description\":\"Програма вступного іспиту до магістратури.\",\"descriptionEn\":\"Master programme entry exam syllabus.\",\"programmeFile\":\"$EXAM_PROGRAMME_DOC_4_ID\",\"order\":4}" \
  "{\"status\":\"published\",\"subjectEn\":\"Pedagogy\",\"description\":\"Програма вступного іспиту до магістратури.\",\"descriptionEn\":\"Master programme entry exam syllabus.\",\"programmeFile\":\"$EXAM_PROGRAMME_DOC_4_ID\",\"order\":4}" \
  >/dev/null

upsert_single "admission_exam_programs" \
  "/items/admission_exam_programs?filter%5Bsubject%5D%5B_eq%5D=Комп'ютерні%20науки&filter%5Blevel%5D%5B_eq%5D=master&fields=id&limit=1" \
  "{\"status\":\"published\",\"subject\":\"Комп'ютерні науки\",\"subjectEn\":\"Computer science\",\"level\":\"master\",\"description\":\"Програма фахового іспиту для ІТ-напрямів.\",\"descriptionEn\":\"Professional exam programme for IT applicants.\",\"programmeFile\":\"$EXAM_PROGRAMME_DOC_5_ID\",\"order\":5}" \
  "{\"status\":\"published\",\"subjectEn\":\"Computer science\",\"description\":\"Програма фахового іспиту для ІТ-напрямів.\",\"descriptionEn\":\"Professional exam programme for IT applicants.\",\"programmeFile\":\"$EXAM_PROGRAMME_DOC_5_ID\",\"order\":5}" \
  >/dev/null

upsert_single "admission_exam_programs" \
  "/items/admission_exam_programs?filter%5Bsubject%5D%5B_eq%5D=Психологія&filter%5Blevel%5D%5B_eq%5D=graduate&fields=id&limit=1" \
  "{\"status\":\"published\",\"subject\":\"Психологія\",\"subjectEn\":\"Psychology\",\"level\":\"graduate\",\"description\":\"Програма вступного іспиту до аспірантури.\",\"descriptionEn\":\"Graduate school entry exam programme.\",\"programmeFile\":\"$EXAM_PROGRAMME_DOC_6_ID\",\"order\":6}" \
  "{\"status\":\"published\",\"subjectEn\":\"Psychology\",\"description\":\"Програма вступного іспиту до аспірантури.\",\"descriptionEn\":\"Graduate school entry exam programme.\",\"programmeFile\":\"$EXAM_PROGRAMME_DOC_6_ID\",\"order\":6}" \
  >/dev/null

log "Upserting university orders..."
upsert_single "university_orders" \
  "/items/university_orders?filter%5BorderNumber%5D%5B_eq%5D=001-2024&fields=id&limit=1" \
  "{\"status\":\"published\",\"orderNumber\":\"001-2024\",\"orderDate\":\"2024-01-15\",\"title\":\"Про організацію освітнього процесу\",\"titleEn\":\"On organizing educational process\",\"category\":\"Освітня діяльність\",\"categoryEn\":\"Academic operations\",\"year\":2024,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_1_ID\",\"order\":1}" \
  "{\"status\":\"published\",\"orderDate\":\"2024-01-15\",\"title\":\"Про організацію освітнього процесу\",\"titleEn\":\"On organizing educational process\",\"category\":\"Освітня діяльність\",\"categoryEn\":\"Academic operations\",\"year\":2024,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_1_ID\",\"order\":1}" \
  >/dev/null

upsert_single "university_orders" \
  "/items/university_orders?filter%5BorderNumber%5D%5B_eq%5D=002-2024&fields=id&limit=1" \
  "{\"status\":\"published\",\"orderNumber\":\"002-2024\",\"orderDate\":\"2024-03-04\",\"title\":\"Про затвердження складу вчених рад\",\"titleEn\":\"On approval of academic councils\",\"category\":\"Управління\",\"categoryEn\":\"Governance\",\"year\":2024,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_2_ID\",\"order\":2}" \
  "{\"status\":\"published\",\"orderDate\":\"2024-03-04\",\"title\":\"Про затвердження складу вчених рад\",\"titleEn\":\"On approval of academic councils\",\"category\":\"Управління\",\"categoryEn\":\"Governance\",\"year\":2024,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_2_ID\",\"order\":2}" \
  >/dev/null

upsert_single "university_orders" \
  "/items/university_orders?filter%5BorderNumber%5D%5B_eq%5D=003-2024&fields=id&limit=1" \
  "{\"status\":\"published\",\"orderNumber\":\"003-2024\",\"orderDate\":\"2024-09-02\",\"title\":\"Про початок 2024/2025 навчального року\",\"titleEn\":\"On start of 2024/2025 academic year\",\"category\":\"Освітня діяльність\",\"categoryEn\":\"Academic operations\",\"year\":2024,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_3_ID\",\"order\":3}" \
  "{\"status\":\"published\",\"orderDate\":\"2024-09-02\",\"title\":\"Про початок 2024/2025 навчального року\",\"titleEn\":\"On start of 2024/2025 academic year\",\"category\":\"Освітня діяльність\",\"categoryEn\":\"Academic operations\",\"year\":2024,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_3_ID\",\"order\":3}" \
  >/dev/null

upsert_single "university_orders" \
  "/items/university_orders?filter%5BorderNumber%5D%5B_eq%5D=001-2025&fields=id&limit=1" \
  "{\"status\":\"published\",\"orderNumber\":\"001-2025\",\"orderDate\":\"2025-01-20\",\"title\":\"Про бюджетне планування\",\"titleEn\":\"On budget planning\",\"category\":\"Фінанси\",\"categoryEn\":\"Finance\",\"year\":2025,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_4_ID\",\"order\":4}" \
  "{\"status\":\"published\",\"orderDate\":\"2025-01-20\",\"title\":\"Про бюджетне планування\",\"titleEn\":\"On budget planning\",\"category\":\"Фінанси\",\"categoryEn\":\"Finance\",\"year\":2025,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_4_ID\",\"order\":4}" \
  >/dev/null

upsert_single "university_orders" \
  "/items/university_orders?filter%5BorderNumber%5D%5B_eq%5D=002-2025&fields=id&limit=1" \
  "{\"status\":\"published\",\"orderNumber\":\"002-2025\",\"orderDate\":\"2025-04-07\",\"title\":\"Про проведення практик\",\"titleEn\":\"On internship period organization\",\"category\":\"Освітня діяльність\",\"categoryEn\":\"Academic operations\",\"year\":2025,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_5_ID\",\"order\":5}" \
  "{\"status\":\"published\",\"orderDate\":\"2025-04-07\",\"title\":\"Про проведення практик\",\"titleEn\":\"On internship period organization\",\"category\":\"Освітня діяльність\",\"categoryEn\":\"Academic operations\",\"year\":2025,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_5_ID\",\"order\":5}" \
  >/dev/null

upsert_single "university_orders" \
  "/items/university_orders?filter%5BorderNumber%5D%5B_eq%5D=003-2025&fields=id&limit=1" \
  "{\"status\":\"published\",\"orderNumber\":\"003-2025\",\"orderDate\":\"2025-10-01\",\"title\":\"Про посилення якості освітніх програм\",\"titleEn\":\"On improving programme quality\",\"category\":\"Якість освіти\",\"categoryEn\":\"Education quality\",\"year\":2025,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_6_ID\",\"order\":6}" \
  "{\"status\":\"published\",\"orderDate\":\"2025-10-01\",\"title\":\"Про посилення якості освітніх програм\",\"titleEn\":\"On improving programme quality\",\"category\":\"Якість освіти\",\"categoryEn\":\"Education quality\",\"year\":2025,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_6_ID\",\"order\":6}" \
  >/dev/null

upsert_single "university_orders" \
  "/items/university_orders?filter%5BorderNumber%5D%5B_eq%5D=001-2026&fields=id&limit=1" \
  "{\"status\":\"published\",\"orderNumber\":\"001-2026\",\"orderDate\":\"2026-02-03\",\"title\":\"Про оновлення цифрової інфраструктури\",\"titleEn\":\"On digital infrastructure update\",\"category\":\"ІТ\",\"categoryEn\":\"IT\",\"year\":2026,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_7_ID\",\"order\":7}" \
  "{\"status\":\"published\",\"orderDate\":\"2026-02-03\",\"title\":\"Про оновлення цифрової інфраструктури\",\"titleEn\":\"On digital infrastructure update\",\"category\":\"ІТ\",\"categoryEn\":\"IT\",\"year\":2026,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_7_ID\",\"order\":7}" \
  >/dev/null

upsert_single "university_orders" \
  "/items/university_orders?filter%5BorderNumber%5D%5B_eq%5D=002-2026&fields=id&limit=1" \
  "{\"status\":\"published\",\"orderNumber\":\"002-2026\",\"orderDate\":\"2026-05-12\",\"title\":\"Про проведення вступної кампанії\",\"titleEn\":\"On admission campaign management\",\"category\":\"Приймальна кампанія\",\"categoryEn\":\"Admissions\",\"year\":2026,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_8_ID\",\"order\":8}" \
  "{\"status\":\"published\",\"orderDate\":\"2026-05-12\",\"title\":\"Про проведення вступної кампанії\",\"titleEn\":\"On admission campaign management\",\"category\":\"Приймальна кампанія\",\"categoryEn\":\"Admissions\",\"year\":2026,\"documentFile\":\"$UNIVERSITY_ORDER_DOC_8_ID\",\"order\":8}" \
  >/dev/null

log "Upserting prozorro procurements..."
upsert_single "prozorro_procurements" \
  "/items/prozorro_procurements?filter%5BtenderNumber%5D%5B_eq%5D=UA-2026-01-15-000001-a&fields=id&limit=1" \
  '{"status":"published","tenderNumber":"UA-2026-01-15-000001-a","title":"Закупівля комп'\''ютерної техніки","titleEn":"Computer equipment procurement","amount":1250000,"currency":"UAH","procurementDate":"2026-01-15","state":"completed","prozorroUrl":"https://prozorro.gov.ua/tender/UA-2026-01-15-000001-a","order":1}' \
  '{"status":"published","title":"Закупівля комп'\''ютерної техніки","titleEn":"Computer equipment procurement","amount":1250000,"currency":"UAH","procurementDate":"2026-01-15","state":"completed","prozorroUrl":"https://prozorro.gov.ua/tender/UA-2026-01-15-000001-a","order":1}' \
  >/dev/null

upsert_single "prozorro_procurements" \
  "/items/prozorro_procurements?filter%5BtenderNumber%5D%5B_eq%5D=UA-2026-02-20-000002-a&fields=id&limit=1" \
  '{"status":"published","tenderNumber":"UA-2026-02-20-000002-a","title":"Поточний ремонт навчальних аудиторій","titleEn":"Classroom renovation","amount":940000,"currency":"UAH","procurementDate":"2026-02-20","state":"active","prozorroUrl":"https://prozorro.gov.ua/tender/UA-2026-02-20-000002-a","order":2}' \
  '{"status":"published","title":"Поточний ремонт навчальних аудиторій","titleEn":"Classroom renovation","amount":940000,"currency":"UAH","procurementDate":"2026-02-20","state":"active","prozorroUrl":"https://prozorro.gov.ua/tender/UA-2026-02-20-000002-a","order":2}' \
  >/dev/null

upsert_single "prozorro_procurements" \
  "/items/prozorro_procurements?filter%5BtenderNumber%5D%5B_eq%5D=UA-2026-03-03-000003-a&fields=id&limit=1" \
  '{"status":"published","tenderNumber":"UA-2026-03-03-000003-a","title":"Закупівля ліцензійного програмного забезпечення","titleEn":"Licensed software procurement","amount":510000,"currency":"UAH","procurementDate":"2026-03-03","state":"planned","prozorroUrl":"https://prozorro.gov.ua/tender/UA-2026-03-03-000003-a","order":3}' \
  '{"status":"published","title":"Закупівля ліцензійного програмного забезпечення","titleEn":"Licensed software procurement","amount":510000,"currency":"UAH","procurementDate":"2026-03-03","state":"planned","prozorroUrl":"https://prozorro.gov.ua/tender/UA-2026-03-03-000003-a","order":3}' \
  >/dev/null

upsert_single "prozorro_procurements" \
  "/items/prozorro_procurements?filter%5BtenderNumber%5D%5B_eq%5D=UA-2026-03-30-000004-a&fields=id&limit=1" \
  '{"status":"published","tenderNumber":"UA-2026-03-30-000004-a","title":"Послуги охорони кампусу","titleEn":"Campus security services","amount":670000,"currency":"UAH","procurementDate":"2026-03-30","state":"completed","prozorroUrl":"https://prozorro.gov.ua/tender/UA-2026-03-30-000004-a","order":4}' \
  '{"status":"published","title":"Послуги охорони кампусу","titleEn":"Campus security services","amount":670000,"currency":"UAH","procurementDate":"2026-03-30","state":"completed","prozorroUrl":"https://prozorro.gov.ua/tender/UA-2026-03-30-000004-a","order":4}' \
  >/dev/null

upsert_single "prozorro_procurements" \
  "/items/prozorro_procurements?filter%5BtenderNumber%5D%5B_eq%5D=UA-2026-04-18-000005-a&fields=id&limit=1" \
  '{"status":"published","tenderNumber":"UA-2026-04-18-000005-a","title":"Придбання лабораторного обладнання","titleEn":"Laboratory equipment procurement","amount":780000,"currency":"UAH","procurementDate":"2026-04-18","state":"active","prozorroUrl":"https://prozorro.gov.ua/tender/UA-2026-04-18-000005-a","order":5}' \
  '{"status":"published","title":"Придбання лабораторного обладнання","titleEn":"Laboratory equipment procurement","amount":780000,"currency":"UAH","procurementDate":"2026-04-18","state":"active","prozorroUrl":"https://prozorro.gov.ua/tender/UA-2026-04-18-000005-a","order":5}' \
  >/dev/null

upsert_single "prozorro_procurements" \
  "/items/prozorro_procurements?filter%5BtenderNumber%5D%5B_eq%5D=UA-2026-05-05-000006-a&fields=id&limit=1" \
  '{"status":"published","tenderNumber":"UA-2026-05-05-000006-a","title":"Поставка меблів для гуртожитку","titleEn":"Dormitory furniture supply","amount":430000,"currency":"UAH","procurementDate":"2026-05-05","state":"planned","prozorroUrl":"https://prozorro.gov.ua/tender/UA-2026-05-05-000006-a","order":6}' \
  '{"status":"published","title":"Поставка меблів для гуртожитку","titleEn":"Dormitory furniture supply","amount":430000,"currency":"UAH","procurementDate":"2026-05-05","state":"planned","prozorroUrl":"https://prozorro.gov.ua/tender/UA-2026-05-05-000006-a","order":6}' \
  >/dev/null

log "Upserting science defenses..."
upsert_single "science_defenses" \
  "/items/science_defenses?filter%5BcandidateName%5D%5B_eq%5D=Іваненко%20Марія%20Олегівна&fields=id&limit=1" \
  '{"status":"published","candidateName":"Іваненко Марія Олегівна","candidateNameEn":"Mariia Ivanenko","dissertationTitle":"Формування цифрової компетентності майбутніх учителів","dissertationTitleEn":"Digital competency development of future teachers","specialty":"011 Освітні, педагогічні науки","specialtyEn":"011 Educational Sciences","defenseDate":"2026-06-18T11:00:00.000Z","board":"Спецрада Д 64.053.01","boardEn":"Board D 64.053.01","result":"Очікується","resultEn":"Pending","isUpcoming":true,"order":1}' \
  '{"status":"published","candidateNameEn":"Mariia Ivanenko","dissertationTitle":"Формування цифрової компетентності майбутніх учителів","dissertationTitleEn":"Digital competency development of future teachers","specialty":"011 Освітні, педагогічні науки","specialtyEn":"011 Educational Sciences","defenseDate":"2026-06-18T11:00:00.000Z","board":"Спецрада Д 64.053.01","boardEn":"Board D 64.053.01","result":"Очікується","resultEn":"Pending","isUpcoming":true,"order":1}' \
  >/dev/null

upsert_single "science_defenses" \
  "/items/science_defenses?filter%5BcandidateName%5D%5B_eq%5D=Петренко%20Андрій%20Сергійович&fields=id&limit=1" \
  '{"status":"published","candidateName":"Петренко Андрій Сергійович","candidateNameEn":"Andrii Petrenko","dissertationTitle":"Моделі адаптивного навчання у вищій школі","dissertationTitleEn":"Adaptive learning models in higher education","specialty":"015 Професійна освіта","specialtyEn":"015 Professional Education","defenseDate":"2026-07-03T10:00:00.000Z","board":"Спецрада Д 64.053.02","boardEn":"Board D 64.053.02","result":"Очікується","resultEn":"Pending","isUpcoming":true,"order":2}' \
  '{"status":"published","candidateNameEn":"Andrii Petrenko","dissertationTitle":"Моделі адаптивного навчання у вищій школі","dissertationTitleEn":"Adaptive learning models in higher education","specialty":"015 Професійна освіта","specialtyEn":"015 Professional Education","defenseDate":"2026-07-03T10:00:00.000Z","board":"Спецрада Д 64.053.02","boardEn":"Board D 64.053.02","result":"Очікується","resultEn":"Pending","isUpcoming":true,"order":2}' \
  >/dev/null

upsert_single "science_defenses" \
  "/items/science_defenses?filter%5BcandidateName%5D%5B_eq%5D=Сидоренко%20Олена%20Петрівна&fields=id&limit=1" \
  '{"status":"published","candidateName":"Сидоренко Олена Петрівна","candidateNameEn":"Olena Sydorenko","dissertationTitle":"Психологічна підтримка студентів у кризових умовах","dissertationTitleEn":"Psychological support for students in crisis conditions","specialty":"053 Психологія","specialtyEn":"053 Psychology","defenseDate":"2025-11-12T12:00:00.000Z","board":"Спецрада Д 64.053.03","boardEn":"Board D 64.053.03","result":"Захищено","resultEn":"Defended","isUpcoming":false,"order":3}' \
  '{"status":"published","candidateNameEn":"Olena Sydorenko","dissertationTitle":"Психологічна підтримка студентів у кризових умовах","dissertationTitleEn":"Psychological support for students in crisis conditions","specialty":"053 Психологія","specialtyEn":"053 Psychology","defenseDate":"2025-11-12T12:00:00.000Z","board":"Спецрада Д 64.053.03","boardEn":"Board D 64.053.03","result":"Захищено","resultEn":"Defended","isUpcoming":false,"order":3}' \
  >/dev/null

upsert_single "science_defenses" \
  "/items/science_defenses?filter%5BcandidateName%5D%5B_eq%5D=Кравець%20Дмитро%20Ігорович&fields=id&limit=1" \
  '{"status":"published","candidateName":"Кравець Дмитро Ігорович","candidateNameEn":"Dmytro Kravets","dissertationTitle":"Інклюзивні практики в сучасній школі","dissertationTitleEn":"Inclusive practices in modern school","specialty":"013 Початкова освіта","specialtyEn":"013 Primary Education","defenseDate":"2025-09-25T11:30:00.000Z","board":"Спецрада Д 64.053.04","boardEn":"Board D 64.053.04","result":"Захищено","resultEn":"Defended","isUpcoming":false,"order":4}' \
  '{"status":"published","candidateNameEn":"Dmytro Kravets","dissertationTitle":"Інклюзивні практики в сучасній школі","dissertationTitleEn":"Inclusive practices in modern school","specialty":"013 Початкова освіта","specialtyEn":"013 Primary Education","defenseDate":"2025-09-25T11:30:00.000Z","board":"Спецрада Д 64.053.04","boardEn":"Board D 64.053.04","result":"Захищено","resultEn":"Defended","isUpcoming":false,"order":4}' \
  >/dev/null

log "Upserting science conferences..."
upsert_single "science_conferences" \
  "/items/science_conferences?filter%5Btitle%5D%5B_eq%5D=Міжнародна%20конференція%20з%20цифрової%20педагогіки&fields=id&limit=1" \
  '{"status":"published","title":"Міжнародна конференція з цифрової педагогіки","titleEn":"International Conference on Digital Pedagogy","description":"Обговорення інновацій у викладанні та EdTech.","descriptionEn":"Discussion of teaching innovations and EdTech.","conferenceType":"international","location":"Харків","locationEn":"Kharkiv","eventDate":"2026-10-14T09:00:00.000Z","isUpcoming":true,"participantsSummary":"Очікується 250 учасників","participantsSummaryEn":"Expected 250 participants","order":1}' \
  '{"status":"published","titleEn":"International Conference on Digital Pedagogy","description":"Обговорення інновацій у викладанні та EdTech.","descriptionEn":"Discussion of teaching innovations and EdTech.","conferenceType":"international","location":"Харків","locationEn":"Kharkiv","eventDate":"2026-10-14T09:00:00.000Z","isUpcoming":true,"participantsSummary":"Очікується 250 учасників","participantsSummaryEn":"Expected 250 participants","order":1}' \
  >/dev/null

upsert_single "science_conferences" \
  "/items/science_conferences?filter%5Btitle%5D%5B_eq%5D=Всеукраїнський%20форум%20молодих%20науковців&fields=id&limit=1" \
  '{"status":"published","title":"Всеукраїнський форум молодих науковців","titleEn":"National Forum of Young Researchers","description":"Платформа для презентації студентських досліджень.","descriptionEn":"Platform for student research presentations.","conferenceType":"national","location":"Київ","locationEn":"Kyiv","eventDate":"2026-09-21T10:00:00.000Z","isUpcoming":true,"participantsSummary":"120 тез доповідей","participantsSummaryEn":"120 submitted abstracts","order":2}' \
  '{"status":"published","titleEn":"National Forum of Young Researchers","description":"Платформа для презентації студентських досліджень.","descriptionEn":"Platform for student research presentations.","conferenceType":"national","location":"Київ","locationEn":"Kyiv","eventDate":"2026-09-21T10:00:00.000Z","isUpcoming":true,"participantsSummary":"120 тез доповідей","participantsSummaryEn":"120 submitted abstracts","order":2}' \
  >/dev/null

upsert_single "science_conferences" \
  "/items/science_conferences?filter%5Btitle%5D%5B_eq%5D=Семінар%20з%20прикладної%20лінгвістики&fields=id&limit=1" \
  '{"status":"published","title":"Семінар з прикладної лінгвістики","titleEn":"Applied Linguistics Seminar","description":"Науково-методичний семінар для викладачів.","descriptionEn":"Research and methodology seminar for lecturers.","conferenceType":"university","location":"Харків","locationEn":"Kharkiv","eventDate":"2026-05-27T09:30:00.000Z","isUpcoming":true,"participantsSummary":"40 учасників","participantsSummaryEn":"40 participants","order":3}' \
  '{"status":"published","titleEn":"Applied Linguistics Seminar","description":"Науково-методичний семінар для викладачів.","descriptionEn":"Research and methodology seminar for lecturers.","conferenceType":"university","location":"Харків","locationEn":"Kharkiv","eventDate":"2026-05-27T09:30:00.000Z","isUpcoming":true,"participantsSummary":"40 учасників","participantsSummaryEn":"40 participants","order":3}' \
  >/dev/null

upsert_single "science_conferences" \
  "/items/science_conferences?filter%5Btitle%5D%5B_eq%5D=Конференція%20з%20психології%20освіти%202025&fields=id&limit=1" \
  '{"status":"published","title":"Конференція з психології освіти 2025","titleEn":"Education Psychology Conference 2025","description":"Практики психологічного супроводу в освіті.","descriptionEn":"Practices of psychological support in education.","conferenceType":"national","location":"Львів","locationEn":"Lviv","eventDate":"2025-10-08T10:00:00.000Z","isUpcoming":false,"participantsSummary":"Понад 180 учасників","participantsSummaryEn":"More than 180 participants","order":4}' \
  '{"status":"published","titleEn":"Education Psychology Conference 2025","description":"Практики психологічного супроводу в освіті.","descriptionEn":"Practices of psychological support in education.","conferenceType":"national","location":"Львів","locationEn":"Lviv","eventDate":"2025-10-08T10:00:00.000Z","isUpcoming":false,"participantsSummary":"Понад 180 учасників","participantsSummaryEn":"More than 180 participants","order":4}' \
  >/dev/null

upsert_single "science_conferences" \
  "/items/science_conferences?filter%5Btitle%5D%5B_eq%5D=Освітні%20дані%20та%20аналітика%202024&fields=id&limit=1" \
  '{"status":"published","title":"Освітні дані та аналітика 2024","titleEn":"Education Data and Analytics 2024","description":"Конференція щодо аналітики навчальних результатів.","descriptionEn":"Conference on learning analytics and educational outcomes.","conferenceType":"international","location":"Одеса","locationEn":"Odesa","eventDate":"2024-11-19T09:00:00.000Z","isUpcoming":false,"participantsSummary":"15 університетів-учасників","participantsSummaryEn":"15 participating universities","order":5}' \
  '{"status":"published","titleEn":"Education Data and Analytics 2024","description":"Конференція щодо аналітики навчальних результатів.","descriptionEn":"Conference on learning analytics and educational outcomes.","conferenceType":"international","location":"Одеса","locationEn":"Odesa","eventDate":"2024-11-19T09:00:00.000Z","isUpcoming":false,"participantsSummary":"15 університетів-учасників","participantsSummaryEn":"15 participating universities","order":5}' \
  >/dev/null

log "Upserting financial reports..."
upsert_single "financial_reports" \
  "/items/financial_reports?filter%5BreportYear%5D%5B_eq%5D=2023&fields=id&limit=1" \
  "{\"status\":\"published\",\"reportYear\":2023,\"title\":\"Фінансовий звіт за 2023 рік\",\"titleEn\":\"Financial report for 2023\",\"summary\":\"Стабільне фінансування навчального процесу та модернізації.\",\"summaryEn\":\"Stable funding of academic process and modernization.\",\"revenue\":125400000,\"expenses\":119800000,\"stateFunding\":98200000,\"ownRevenue\":27200000,\"reportFile\":\"$FINANCIAL_REPORT_DOC_2023_ID\",\"order\":1}" \
  "{\"status\":\"published\",\"title\":\"Фінансовий звіт за 2023 рік\",\"titleEn\":\"Financial report for 2023\",\"summary\":\"Стабільне фінансування навчального процесу та модернізації.\",\"summaryEn\":\"Stable funding of academic process and modernization.\",\"revenue\":125400000,\"expenses\":119800000,\"stateFunding\":98200000,\"ownRevenue\":27200000,\"reportFile\":\"$FINANCIAL_REPORT_DOC_2023_ID\",\"order\":1}" \
  >/dev/null

upsert_single "financial_reports" \
  "/items/financial_reports?filter%5BreportYear%5D%5B_eq%5D=2024&fields=id&limit=1" \
  "{\"status\":\"published\",\"reportYear\":2024,\"title\":\"Фінансовий звіт за 2024 рік\",\"titleEn\":\"Financial report for 2024\",\"summary\":\"Збільшено видатки на інфраструктуру та цифрові сервіси.\",\"summaryEn\":\"Increased spending on infrastructure and digital services.\",\"revenue\":138900000,\"expenses\":132700000,\"stateFunding\":104300000,\"ownRevenue\":34600000,\"reportFile\":\"$FINANCIAL_REPORT_DOC_2024_ID\",\"order\":2}" \
  "{\"status\":\"published\",\"title\":\"Фінансовий звіт за 2024 рік\",\"titleEn\":\"Financial report for 2024\",\"summary\":\"Збільшено видатки на інфраструктуру та цифрові сервіси.\",\"summaryEn\":\"Increased spending on infrastructure and digital services.\",\"revenue\":138900000,\"expenses\":132700000,\"stateFunding\":104300000,\"ownRevenue\":34600000,\"reportFile\":\"$FINANCIAL_REPORT_DOC_2024_ID\",\"order\":2}" \
  >/dev/null

upsert_single "financial_reports" \
  "/items/financial_reports?filter%5BreportYear%5D%5B_eq%5D=2025&fields=id&limit=1" \
  "{\"status\":\"published\",\"reportYear\":2025,\"title\":\"Фінансовий звіт за 2025 рік\",\"titleEn\":\"Financial report for 2025\",\"summary\":\"Пріоритет — академічна якість, стипендіальні програми та наука.\",\"summaryEn\":\"Priority areas include academic quality, scholarships, and research.\",\"revenue\":146800000,\"expenses\":140200000,\"stateFunding\":109500000,\"ownRevenue\":37300000,\"reportFile\":\"$FINANCIAL_REPORT_DOC_2025_ID\",\"order\":3}" \
  "{\"status\":\"published\",\"title\":\"Фінансовий звіт за 2025 рік\",\"titleEn\":\"Financial report for 2025\",\"summary\":\"Пріоритет — академічна якість, стипендіальні програми та наука.\",\"summaryEn\":\"Priority areas include academic quality, scholarships, and research.\",\"revenue\":146800000,\"expenses\":140200000,\"stateFunding\":109500000,\"ownRevenue\":37300000,\"reportFile\":\"$FINANCIAL_REPORT_DOC_2025_ID\",\"order\":3}" \
  >/dev/null

log "Seed complete."
